### ISSUE TITLE
Set nosmartindent to avoid comments auto-indenting to first column

### ISSUE THREAD

**Issue by memeplex** [hynek/vim-python-pep8-indent#46] opened 2015-07-20 19:52 UTC
For example, the cursor being `^`:

```
def test():
    ^
```

say you now type `#`, you get:

```
def test():
#
```

instead of:

```
def test():
    #
```

The reason is smartindent. I think your indent plugin should un`setlocal` it by default.

**Comment by blueyed** [comment] 2015-07-20 21:24
Agreed, without having looked into it.

Should be a trivial change (which should include a test).  A PR for this would be welcome, of course!

**Comment by blueyed** [comment] 2016-06-26 13:41
I could not reproduce it, using both `smartindent` and `set indentexpr+=#`.

**Comment by hynek** [comment] 2016-07-03 07:48
Closing then.  Feel free to re-open if we missed something.

**Closed by hynek** 2016-07-03 07:48 UTC
Labels: bug, enhancement

**Comment by bharadwaj-raju** [comment] 2016-09-16 16:50
Note that this can fix it without disabling `smartindent`:

`inoremap # X<BS>#`

**Comment by blueyed** [comment] 2016-09-16 20:04
@bharadwaj-raju 
So you can reproduce this?
Do you have `#` in `:set indentkeys?`?

**Comment by bharadwaj-raju** [comment] 2016-09-17 06:56
Yes, I can. I don't have `#` in `indentkeys`.

Removing the `inoremap` and adding `#` to `indentkeys` re-introduces the problem.

**Comment by blueyed** [comment] 2016-09-17 09:12
What Vim/Neovim version?
'smartindent' is set, right?
Other settings that might be involved?!

**Comment by bharadwaj-raju** [comment] 2016-09-17 09:25
Smartindent is set.

```
NVIM 0.1.5
Build type: RelWithDebInfo
Compilation: /usr/bin/cc -march=x86-64 -mtune=generic -O2 -pipe -fstack-protector-strong -Wconversion -O2 -g -DDISABLE_LOG -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wvla -fstack-protector-strong -fdiagnostics-color=auto -DINCLUDE_GENERATED_DECLARATIONS -DHAVE_CONFIG_H -D_GNU_SOURCE -I/build/neovim/src/build/config -I/build/neovim/src/neovim-0.1.5/src -I/usr/include -I/usr/include -I/usr/include -I/usr/include -I/usr/include -I/usr/include -I/usr/include -I/build/neovim/src/build/src/nvim/auto -I/build/neovim/src/build/include
Compiled by builduser

Optional features included (+) or not (-): +acl   +iconv    +jemalloc +tui      
For differences from Vim, see :help vim-differences

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/usr/share/nvim"
```

**Comment by blueyed** [comment] 2016-09-17 09:31
I could still not reproduce it yesterday. Can you try it with a minimal init.vim, please, and provide this here?!

**Comment by bharadwaj-raju** [comment] 2016-09-17 10:48
`/tmp/minimalvimrc`:

```vim
set nocompatible

syntax on

filetype plugin on

set smartindent

set smartindent cinwords=if,else,try,except,finally,while,for,def,class
```

    $ nvim -u /tmp/minimalvimrc /tmp/test.py

Reproducible.

**Comment by blueyed** [comment] 2016-09-18 00:15
Thanks for the test case.

As we can see it's not caused by this plugin (which I assumed).

From `:h 'smartindent'`:

>         When typing '#' as the first character in a new line, the indent for
        that line is removed, the '#' is put in the first column.  The indent
        is restored for the next line.  If you don't want this, use this
        mapping: ":inoremap # X^H#", where ^H is entered with CTRL-V CTRL-H.

Which is what you suggested.

I could imagine adding this to Python buffers via `ftplugin/python.vim` if `smartindent` is enabled, but that should be done for Vim by default then probably?!
